MT32603: Upgrade symfony from version 4.4 to 5.4
 - Fix unit tests

Failed to start the session because headers have already been sent by "/home/planningb/www/planningbiblio/vendor/phpunit/phpunit/src/Util/Printer.php" at line 104.
=> storage_factory_id from native to php_bridge

Undefined array key "Auth-Mode"
Undefined array key "login_id"
=> define session values in PLBWebTestCase::setUp

TypeError: App\EventListener\ControllerAuthorizationListener::triggerAccessDenied(): Argument #1 ($event) must be of type App\EventListener\GetResponseEvent, Symfony\Component\HttpKernel\Event\RequestEvent given, called in /home/planno/www/planno/src/EventListener/ControllerAuthorizationListener.php on line 72
=> change triggerAccessDenied signature